# Generated by Django 4.0.7 on 2023-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_o_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_details',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
