# Generated by Django 4.0.7 on 2023-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_alter_o_details_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_details',
            name='file2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
