# Generated by Django 4.0.7 on 2023-01-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_o_details_file2'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
