# Generated by Django 4.0.7 on 2023-01-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_o_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_purpose',
            name='certified',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='notcertified',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='organisation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='purpose',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='quantaity',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='query',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='o_purpose',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
