# Generated by Django 4.0.7 on 2023-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_o_purpose_certified_o_purpose_notcertified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_purpose',
            name='solutions',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
