# Generated by Django 4.0.7 on 2023-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_o_purpose_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_details',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
