# Generated by Django 4.0.6 on 2023-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_o_details_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_register',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
