# Generated by Django 4.0.6 on 2023-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_org_register_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_purpose',
            name='boolean1',
            field=models.BooleanField(default=False),
        ),
    ]
