# Generated by Django 4.0.6 on 2023-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_r_isotope'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_isotope',
            name='solution',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
