# Generated by Django 4.0.7 on 2023-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cypher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cypher_admin_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('adminfile', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
