# Generated by Django 4.0.6 on 2023-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_rqst',
            old_name='Purpose',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='admin_rqst',
            name='email',
        ),
        migrations.AddField(
            model_name='admin_rqst',
            name='organisation',
            field=models.CharField(default='exit', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
